name: Deploy NestJS App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm ci

    - name: Run Tests
      run: npm test

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Install Node.js, npm, and pm2 if not already installed
          if ! command -v node &> /dev/null; then
            curl -fsSL https://rpm.nodesource.com/setup_16.x | sudo bash -
            sudo yum install -y nodejs
          fi

          if ! command -v pm2 &> /dev/null; then
            sudo npm install -g pm2
          fi

          # Navigate to the application directory and pull the latest code
          cd /home/ec2-user/Hello-world
          git pull origin main
          
          # Install dependencies and build the project
          npm ci
          npm run build
          
          # Restart the application with pm2
          pm2 restart "Hello world" || pm2 start dist/main.js --name "Hello world"
