name: Deploy NestJS App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm ci

    - name: Run Tests
      run: npm test

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_USER: ec2-user
        EC2_HOST: ec2-54-159-63-227.compute-1.amazonaws.com
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key $EC2_USER@$EC2_HOST << 'EOF'
          cd /home/ec2-user/Hello-world
          git pull origin main
          npm ci
          npm run build
          pm2 restart "Hello world"
        EOF
